### ISSUE TITLE
UPDATE COMMITS?

### ISSUE THREAD

**Issue by cheateronly123** [n0verify/ftp_loader#23]
When will you release new cheat commits?
Daniel has already posted a bunch of updates, when are they going to include it here on FTP?

@IcyAF @n0verify

**Comment by n0verify** [comment]
i am updating the entire cheat as we speak

**Comment by n0verify** [comment]
> When will you release new cheat commits?
> Daniel has already posted a bunch of updates, when are they going to include it here on FTP?
> 
> @IcyAF @n0verify

the cheat is now on the latest commit
