### ISSUE TITLE
ESP Font Size

### ISSUE THREAD

**Issue by floydGG** [n0verify/ftp_loader#6]
Hey yo, first of all thank you for this good stuff from u.
Is it possible adding ESP Font Size to the Menu?

**Comment by n0verify** [comment]
it is possible, i just have to figure out which fonts in csgo have multiple sizes

**Comment by n0verify** [comment]
> Hey yo, first of all thank you for this good stuff from u.
> Is it possible adding ESP Font Size to the Menu?

Although, in the esp tab there is font selection which allows you to use any game font for esp (there are more than 200 of them, in many sizes).

**Comment by floydGG** [comment]
> > Hey yo, first of all thank you for this good stuff from u.
> > Is it possible adding ESP Font Size to the Menu?
> 
> Although, in the esp tab there is font selection which allows you to use any game font for esp (there are more than 200 of them, in many sizes).

Aight noted, how do i compile this cheats without the loader? And 1 more, release or debug?

**Comment by n0verify** [comment]
> > > Hey yo, first of all thank you for this good stuff from u.
> > > Is it possible adding ESP Font Size to the Menu?
> > 
> > 
> > Although, in the esp tab there is font selection which allows you to use any game font for esp (there are more than 200 of them, in many sizes).
> 
> Aight noted, how do i compile this cheat without the loader? And 1 more, release or debug?

in the solution, just open one of the files of the cheat then go to build -> build ftp_cheat

i build it in debug x86, but if you want release x86, just copy the build configuration over

**Comment by floydGG** [comment]
> > > > Hey yo, first of all thank you for this good stuff from u.
> > > > Is it possible adding ESP Font Size to the Menu?
> > > 
> > > 
> > > Although, in the esp tab there is font selection which allows you to use any game font for esp (there are more than 200 of them, in many sizes).
> > 
> > Aight noted, how do i compile this cheat without the loader? And 1 more, release or debug?
> 
> in the solution, just open one of the files of the cheat then go to build -> build ftp_cheat
> 
> i build it in debug x86, but if you want release x86, just copy the build configuration over

aight, thank you again.
good shit bro 🔥

**Comment by n0verify** [comment]
> > > > > Hey yo, first of all thank you for this good stuff from u.
> > > > > Is it possible adding ESP Font Size to the Menu?
> > > > 
> > > > 
> > > > Although, in the esp tab there is font selection which allows you to use any game font for esp (there are more than 200 of them, in many sizes).
> > > 
> > > 
> > > Aight noted, how do i compile this cheat without the loader? And 1 more, release or debug?
> > 
> > 
> > in the solution, just open one of the files of the cheat then go to build -> build ftp_cheat
> > i build it in debug x86, but if you want release x86, just copy the build configuration over
> 
> aight, thank you again.
> good shit bro 🔥

of course :)
